Lanzamiento versión 0.5.0
IslasGECI/reproducibility_inspector pull request #15
Opened 2021-04-13 19:14 UTC by evaristor

2021-04-15 16:58 UTC, islasfernando requested changes
Queda la duda de si deberíamos intentarlo en el servidor ó local. Si es local parece que se ocupan algunos cambios en el Makefile.

2021-04-15 16:58 UTC, islasfernando commented on Makefile
> +	cat /.vault/.secrets | grep BITBUCKET_USERNAME
Hara falta checar el `BITBUCKET_PASSWORD`?

2021-04-15 16:58 UTC, islasfernando commented on Makefile
> +	[ -d /home/ciencia_datos/.testmake ]
Parece que está escrito para el nombre de usuario del servidor, en todo caso para generalizar debería ser un `pwd` o algo así?

2021-04-15 16:58 UTC, islasfernando commented on README.md
> +1. Crea un archivo con las credenciales del equipo. ([Ver más
Está escrito con el nombre de usuario del servidor, como ejemplo supongo pero hay que decir que ese nombre cambia dependiendo de donde se quieran ejecutar estas instrucciones

2021-04-15 16:58 UTC, islasfernando commented on README.md
> +make --file=build/Makefile container
Busca un nombre de usuario particular, en el servidor funcionaría pero "local" no corren:
```
fer-geci@fernando-ia:~/repos/reproducibility_inspector$ make --file=build/Makefile tests
cat /home/ciencia_datos/.vault/.secrets | grep BITBUCKET_USERNAME
cat: /home/ciencia_datos/.vault/.secrets: No such file or directory
make: *** [build/Makefile:21: test_credentials] Error 1

```

2021-04-15 16:58 UTC, islasfernando commented on README.md
> +1. Crea un archivo con las credenciales del equipo. ([Ver más
En el archivo de [bóveda](https://docs.google.com/document/d/1lY7ycXs4J8wp1OyJCmPsvfB7YdQqscqL52cIZxBP6Rw/edit). Hay que rellenar con las contraseñas correspondientes para el analislas o las personales?
 
Escribe las credenciales del equipo de la manera siguiente:

```
export BITBUCKET_USERNAME=analislas
export BITBUCKET_PASSWORD=<CONTRASEÑA>
export MYSQL_ROOT_PASSWORD=<CONTRASEÑA>
```

2021-04-15 17:10 UTC, evaristor commented
@xwalls: ¿Por favor podrías atender la revisión de @islasfernando?

2021-04-15 17:30 UTC, evaristor commented on Makefile
> +	cat /.vault/.secrets | grep BITBUCKET_USERNAME
Eso deplegaría la contraseña en la terminal, por eso solo verificamos el nombre de usuario.

2021-04-15 19:35 UTC, xwalls commented on Makefile
> +	cat /.vault/.secrets | grep BITBUCKET_USERNAME
esa es la intención de esta primer prueba, verificar que efectivamente está configurada esa variable.

2021-04-15 19:36 UTC, xwalls commented on Makefile
> +	cat /.vault/.secrets | grep BITBUCKET_USERNAME
así como dice evaristo desplegar la otra variable no será necesario

2021-04-15 19:37 UTC, xwalls commented on Makefile
> +	cat /.vault/.secrets | grep BITBUCKET_USERNAME
aun asi se podria considerar para contraseña verificar únicamente que exista un valor asignado ;)

2021-04-15 19:50 UTC, xwalls commented on Makefile
> +	[ -d /home/ciencia_datos/.testmake ]
tienes razón pareciera que solo está diseñado para un único usuario en este caso `ciencia_datos`. sin embargo!
realmente solo es una carpeta específica que podemos crear sin problemas. 

En este caso como el inspector es un motor 'padre' por así decirlo. se me hace acertado que tenga su lugar con sus credenciales dedicadas.

Aunque también se puede optar por esa opción de `/home/<MI_USUARIO>/.testmake`

como la ves tu @evaristor ?

2021-04-15 19:55 UTC, xwalls commented on README.md
> +1. Crea un archivo con las credenciales del equipo. ([Ver más
pienso en que el usuario __analislas__ es un integrante más del equipo y a su nombre es como ejecutamos el inspector de reproducibilidad.

podrías confirmarnos esto @evaristor ?

2021-04-15 19:58 UTC, evaristor commented on Makefile
> +	[ -d /home/ciencia_datos/.testmake ]
La observación de @islasfernando es acertada y los cambios requeridos en el Makefile y README están fáciles.
Sin embargo, la generalización propuesta por @islasfernando implica resolver un problema complicado: los cambios requeridos en las líneas 5 y 7 del Dockerfile y líneas 2 y 4 del Cronfile. No es imposible pero incrementaría considerablemente la complejidad del repo.
En teoría, si se siguen las instrucciones del READEME deberían pasar las pruebas.

2021-04-15 20:00 UTC, xwalls commented on README.md
> +make --file=build/Makefile container
El resultado es correcto, la prueba consiste en tratar de llamar a esa variable, si no la encuentra la prueba no pasará.

Esto relacionado con lo del usuario. pero por el momento nosotros especificamos en las instrucciones que el archivo en la siguiente ruta `/home/ciencia_datos/.vault/.secrets` debe existir y estar configurado. :raised_hands:

2021-04-15 20:02 UTC, evaristor commented on README.md
> +1. Crea un archivo con las credenciales del equipo. ([Ver más
Da lo mismo. Es sólo un ejemplo.

2021-04-16 18:29 UTC, islasfernando approved these changes
Quedó mucho mas claro el README, si pude seguir las instrucciones ✌🏼

2021-04-16 18:30 UTC, merged